<?php
include_once "Circle.php";

class Cylinder extends Circle
{
    public $height;

    public function __construct($radius, $color, $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    public function get_Height()
    {
        return $this->height;
    }

    public function set_Height($height)
    {
        $this->height = $height;
    }

    public function get_Area()
    {
        return 2 * pi() * $this->radius * $this->height;
    }

    public function get_Volume()
    {
        return pi() * $this->radius * $this->radius * $this->height;
    }

    public function ToString()
    {
        parent::ToString(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "Volume is: " . $this->get_Volume();
    }
}

?>