<?php
include_once "Point2D.php";

class Point3D extends Point2D
{
    public $z;

    public function __construct($x, $y, $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    public function get_Z()
    {
        return $this->z;
    }

    public function set_Z($z)
    {
        $this->z = $z;
    }

    public function set_XYZ($x, $y, $z)
    {
        parent::set_XY($x,$y);
        $this->z = $z;
    }

    public function get_XYZ()
    {
        return $arr = array($this->x,$this->y,$this->z);
    }
    public function ToString()
    {
        parent::ToString(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "This Z is: ".$this->z;
    }
}


?>