<?php

class MovablePoint extends Point
{
    public $xSpeed;
    public $ySpeed;

    public function __construct($x, $y, $xSpeed, $ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    public function get_XSpeed()
    {
        return $this->xSpeed;
    }

    public function set_XSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    public function get_YSpeed()
    {
        return $this->ySpeed;
    }

    public function set_YSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }

    public function set_Speed($xspeed, $yspeed)
    {
        $this->xSpeed = $xspeed;
        $this->ySpeed = $yspeed;
    }

    public function get_Speed()
    {
        return $arr = array($this->xSpeed, $this->ySpeed);
    }

    public function ToString()
    {
        parent::ToString(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "XSpeed is: " . $this->get_XSpeed();
        echo "<br>";
        echo "YSpeed is: " . $this->get_YSpeed();
    }
    public function move(){
       echo "MovablePoint X is: ". $this->x += $this->xSpeed;
       echo "<br>";
       echo "MovablePoint Y is: ". $this->y += $this->ySpeed;
    }
}

?>